# Generated by Django 5.2.11 on 2026-02-24 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syndicat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du syndicat')),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='syndicats/logos/', verbose_name='Logo')),
                ('signataire_nom', models.CharField(max_length=100, verbose_name='Nom du signataire')),
                ('signataire_titre', models.CharField(max_length=100, verbose_name='Titre (ex: Président)')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='syndicats/signatures/', verbose_name='Signature (image)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Syndicat',
                'verbose_name_plural': 'Syndicats',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MemberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('syndicat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='syndicat.syndicat', verbose_name='Syndicat')),
            ],
            options={
                'verbose_name': 'Catégorie de membre',
                'verbose_name_plural': 'Catégories de membres',
                'ordering': ['syndicat', 'ordre', 'nom'],
                'unique_together': {('syndicat', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_membre', models.CharField(blank=True, max_length=50, verbose_name='Numéro de membre')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/photos/', verbose_name='Photo')),
                ('date_adhesion', models.DateField(blank=True, null=True, verbose_name="Date d'adhésion")),
                ('actif', models.BooleanField(default=True, verbose_name='Membre actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='syndicat.membercategory', verbose_name='Catégorie')),
                ('syndicat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='syndicat.syndicat', verbose_name='Syndicat')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['syndicat', 'nom', 'prenom'],
            },
        ),
    ]
