# Generated by Django 5.2.11 on 2026-02-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ministere_entreprise',
            field=models.CharField(blank=True, help_text='Ex: ENVIRONNEMENT, Finances...', max_length=200, verbose_name='Ministère / Entreprise'),
        ),
        migrations.AddField(
            model_name='syndicat',
            name='cachet',
            field=models.ImageField(blank=True, help_text='Cachet circulaire pour le RECTO de la carte', null=True, upload_to='syndicats/cachets/', verbose_name='Cachet / Sceau (cercle)'),
        ),
        migrations.AddField(
            model_name='syndicat',
            name='clause_legale',
            field=models.TextField(blank=True, default="Les autorités civiles et militaires sont priées d'apporter toute leur assistance au porteur de la présente.", verbose_name='Clause légale (VERSO)'),
        ),
        migrations.AddField(
            model_name='syndicat',
            name='nom_complet',
            field=models.CharField(blank=True, help_text='Ex: Syndicat Général Administratif...', max_length=400, verbose_name='Nom complet du syndicat'),
        ),
        migrations.AddField(
            model_name='syndicat',
            name='pays',
            field=models.CharField(blank=True, default='République Démocratique du Congo', max_length=200, verbose_name='Pays (pour le VERSO)'),
        ),
        migrations.AlterField(
            model_name='syndicat',
            name='nom',
            field=models.CharField(help_text='Ex: SYGEMIFIN', max_length=200, verbose_name='Nom court / Sigle'),
        ),
        migrations.AlterField(
            model_name='syndicat',
            name='signataire_titre',
            field=models.CharField(max_length=100, verbose_name='Titre (ex: Le Président)'),
        ),
    ]
