# Generated by Django 4.2.7 on 2026-02-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0002_recto_verso'),
    ]

    operations = [
        migrations.AddField(
            model_name='syndicat',
            name='image_fond',
            field=models.ImageField(blank=True, help_text="Image de fond pour le RECTO de la carte. Format clair recommandé pour l'impression.", null=True, upload_to='syndicats/fonds/', verbose_name='Image de fond (carte RECTO)'),
        ),
        migrations.AlterField(
            model_name='syndicat',
            name='cachet',
            field=models.ImageField(blank=True, help_text='Cachet circulaire. Format PNG recommandé (superposé à la signature sur la carte).', null=True, upload_to='syndicats/cachets/', verbose_name='Cachet / Sceau (cercle)'),
        ),
        migrations.AlterField(
            model_name='syndicat',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature. Format PNG recommandé (superposée au cachet sur la carte).', null=True, upload_to='syndicats/signatures/', verbose_name='Signature (image)'),
        ),
    ]
