# Generated by Django 4.2.7 on 2026-02-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0003_add_image_fond'),
    ]

    operations = [
        migrations.AddField(
            model_name='syndicat',
            name='image_fond_verso',
            field=models.ImageField(blank=True, help_text="Image de fond pour le VERSO de la carte. Format clair recommandé pour l'impression.", null=True, upload_to='syndicats/fonds/', verbose_name='Image de fond (carte VERSO)'),
        ),
    ]
