# Generated by Django 4.2.7 on 2026-02-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0004_add_image_fond_verso'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contact_urgence',
            field=models.CharField(blank=True, help_text='Ex: Urgences : +243 82 44 44 808', max_length=200, verbose_name="Contact d'urgence (VERSO)"),
        ),
        migrations.AddField(
            model_name='member',
            name='date_expiration',
            field=models.DateField(blank=True, help_text='Ex: 01-02-2027. Vide = calculée (adhésion + 1 an).', null=True, verbose_name="Date d'expiration de la carte"),
        ),
        migrations.AddField(
            model_name='member',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='member',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, verbose_name='Genre'),
        ),
    ]
