# Generated by Django 4.2.7 on 2026-02-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0005_member_contact_urgence_member_date_expiration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contact_urgence',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='member',
            name='genre',
        ),
    ]
