# Generated by Django 4.2.7 on 2026-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0006_remove_modelecarte_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='generated_card',
            field=models.ImageField(blank=True, null=True, upload_to='membres/cartes/', verbose_name='Carte RECTO générée'),
        ),
        migrations.AddField(
            model_name='member',
            name='generated_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='membres/cartes/', verbose_name='Carte VERSO générée'),
        ),
    ]
