# Generated by Django 4.2.7 on 2026-03-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0007_add_generated_card_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom de la banque')),
            ],
            options={
                'verbose_name': 'Banque',
                'verbose_name_plural': 'Banques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MatriculeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code matricule')),
            ],
            options={
                'verbose_name': 'Option matricule',
                'verbose_name_plural': 'Options matricule',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='service',
            field=models.CharField(blank=True, max_length=200, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='syndicat',
            name='nom',
            field=models.CharField(help_text='Ex: Sigle du syndicat', max_length=200, verbose_name='Nom court / Sigle'),
        ),
        migrations.AddField(
            model_name='member',
            name='banque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='syndicat.banque', verbose_name='Banque'),
        ),
        migrations.AddField(
            model_name='member',
            name='matricule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='syndicat.matriculeoption', verbose_name='Matricule'),
        ),
    ]
