# Generated by Django 4.2.7 on 2026-03-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0008_add_service_banque_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='matricule',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Matricule'),
        ),
        migrations.DeleteModel(
            name='MatriculeOption',
        ),
    ]
