# Generated by Django 5.2.11 on 2026-03-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0009_matricule_saisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='postnom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Postnom'),
        ),
    ]
